const shared = {
	x: 0,
	y: 0,
	opacity: 1,
	addLabel: true
};

const keys = {
	typeA: {
		leafType: 'typeA',
		leafCount: 39,
		stemRadius: 12, //- 17,
		angleOffset: -1,
		leafLength: 0.5,
		leafWidth: 0.4,
		scalePolicyKey: 'inverseIndex',
		curlInnerLeaves: false,
		leafTiltMin: 14,
		leafTiltMax: 39,
		leafTiltFullRange: 100,
		strokeColourKey: 'darkSeaGreen',
		fillColourKey: 'white',
		strokeColourPolicyKey: 'greenToRed',
		fillColourPolicyKey: 'constant',
		colourChangeRate: 1,
		opacity: 1
	},
	typeB: {
		leafType: 'typeB',
		leafCount: 85,
		stemRadius: 7,
		angleOffset: 1,
		scalePolicyKey: 'inverseIndex',
		curlInnerLeaves: true,
		leafLength: 0.8,
		leafWidth: 0.3,
		leafTiltMin: 104,
		leafTiltMax: 180,
		leafTiltFullRange: 450,
		strokeColourKey: 'paleTurquoise',
		fillColourKey: 'white',
		strokeColourPolicyKey: 'blueToGreen',
		fillColourPolicyKey: 'constant',
		colourChangeRate: 1,
		opacity: 1
	},
	typeC: {
		leafType: 'typeC',
		leafCount: 50,
		stemRadius: 9,
		angleOffset: 1.5,
		scalePolicyKey: 'inverseIndex',
		curlInnerLeaves: true,
		leafLength: 0.6,
		leafWidth: 0.4,
		leafTiltMin: 22,
		leafTiltMax: 96,
		leafTiltFullRange: 128,
		strokeColourKey: 'paleTurquoise',
		fillColourKey: 'white',
		strokeColourPolicyKey: 'blueToGreen',
		fillColourPolicyKey: 'constant',
		colourChangeRate: 1,
		opacity: 1
	},
	typeD: {
		leafType: 'typeD',
		leafCount: 19,
		stemRadius: 0,
		angleOffset: 7.3,
		scalePolicyKey: 'inverseIndex',
		leafLength: 0.7,
		leafWidth: 0.4,
		leafTiltMin: 49,
		leafTiltMax: 64,
		leafTiltFullRange: 164,
		strokeColourPolicyKey: 'greenToRed',
		curlInnerLeaves: false,
		strokeColourKey: 'darkGreen',
		fillColourKey: 'white',
		fillColourPolicyKey: 'constant',
		colourChangeRate: 1
	},
	typeE: {
		leafType: 'typeE',
		leafCount: 25,
		stemRadius: 0,
		angleOffset: 0,
		scalePolicyKey: 'inverseIndex',
		leafLength: 0.45,
		leafWidth: 0.2,
		leafTiltMin: 16,
		leafTiltMax: 47,
		leafTiltFullRange: 63,
		strokeColourPolicyKey: 'greenToRed',
		curlInnerLeaves: true,
		strokeColourKey: 'yellowGreen',
		fillColourKey: 'white',
		fillColourPolicyKey: 'constant',
		colourChangeRate: 2
	},
	typeF: {
		leafType: 'typeF',
		leafCount: 19,
		stemRadius: 3,
		angleOffset: -4.8,
		scalePolicyKey: 'inverseIndex',
		leafLength: 0.7,
		leafWidth: 0.1,
		leafTiltMin: 13,
		leafTiltMax: 47,
		leafTiltFullRange: 63,
		strokeColourPolicyKey: 'blueToGreen',
		curlInnerLeaves: true,
		strokeColourKey: 'darkCyan',
		fillColourKey: 'white',
		fillColourPolicyKey: 'constant',
		colourChangeRate: 4
	},
	typeG: {
		leafType: 'typeG',
		leafCount: 106,
		stemRadius: 22,
		angleOffset: 0,
		scalePolicyKey: 'inverseIndex',
		leafLength: 0.45,
		leafWidth: 0.15,
		leafTiltMin: 19,
		leafTiltMax: 109,
		leafTiltFullRange: 259,
		strokeColourPolicyKey: 'blueToRed',
		curlInnerLeaves: false,
		strokeColourKey: 'paleTurquoise',
		fillColourKey: 'white',
		fillColourPolicyKey: 'constant',
		colourChangeRate: 0.5,
		opacity: 1
	},
	TypeH: {
		leafType: 'typeH',
		leafCount: 128,
		stemRadius: 24,
		angleOffset: 3.7,
		scalePolicyKey: 'inverseIndex',
		leafLength: 1.1,
		leafWidth: 0,
		leafTiltMin: 46,
		leafTiltMax: 140,
		leafTiltFullRange: 295,
		strokeColourPolicyKey: 'greenToRed',
		curlInnerLeaves: true,
		strokeColourKey: 'limeGreen',
		fillColourKey: 'white',
		fillColourPolicyKey: 'constant',
		colourChangeRate: 2.1
	}
};

function load(setId, x, y) {
	return {
		...shared,
		...keys[setId],
		...{ x, y }
	};
}

export default {
	load,
	keys
};
